CREATE DATABASE ENCRYPTPASS
USE ENCRYPTPASS

CREATE TABLE EMPLOYEE
(
ID INT PRIMARY KEY IDENTITY (1,1),
USERNAME VARCHAR(20) UNIQUE,
NAME VARCHAR(50),
EMAIL NVARCHAR(30) UNIQUE,
PASSWORD VARBINARY(8000),
)
GO

CREATE PROCEDURE RegisterEmployee
	@USERNAME VARCHAR(20),
	@NAME VARCHAR(50),
	@EMAIL NVARCHAR(30),
	@PASSWORD NVARCHAR(30)
AS
BEGIN
INSERT INTO EMPLOYEE VALUES
(
	@USERNAME,
	@NAME,
	@EMAIL,
	ENCRYPTBYPASSPHRASE('PASSWORD',@PASSWORD)
)END
GO

EXEC RegisterEmployee 'DantesMx','Victor','dvmx@gmail.com','A$hen0ne3'

select*from EMPLOYEE

select CONVERT(Nvarchar(max), DECRYPTBYPASSPHRASE('PASSWORD',PASSWORD)) from EMPLOYEE