CREATE DATABASE EncripPass
USE EncripPass

CREATE TABLE COMPANY
(
ID INT PRIMARY KEY IDENTITY (1,1),
NAME_C VARCHAR (50),
ADDRESS_C VARCHAR (60),
USERNAME VARCHAR (20) UNIQUE,
PASS VARBINARY (8000)
)
GO

CREATE TABLE EMPLOYEE
(
ID_EMP INT PRIMARY KEY IDENTITY (1,1),
NAME_E VARCHAR (60),
EMAIl NVARCHAR (30) UNIQUE,
ADDRESS_E NVARCHAR (60),
USER_E VARCHAR (60),
PASS_E VARBINARY (8000),
ID INT FOREIGN KEY REFERENCES COMPANY(ID)
)
GO

CREATE TABLE SITEC
(
ID_DITE INT PRIMARY KEY IDENTITY(1,1),
NAME_S NVARCHAR (60),
DESCR VARCHAR (100),
PASS_S VARBINARY (8000),
ID_EMP INT FOREIGN KEY REFERENCES EMPLOYEE (ID_EMP)
)
GO

---// PROCEDIMEINTO ALMACENADO

CREATE PROCEDURE REGISTERCOMPANY
	@NAME_C VARCHAR (50),
	@ADDRESS_C VARCHAR (60),
	@USERNAME VARCHAR (20),
	@PASS NVARCHAR (30)
AS
BEGIN
INSERT INTO COMPANY VALUES
(
	@NAME_C,
	@ADDRESS_C,
	@USERNAME,
	ENCRYPTBYPASSPHRASE('PASSWORD',@PASS)
)
END
GO

CREATE PROCEDURE REGISTEREMPLOYEE
	@NAME_E VARCHAR (60),
	@EMAIL NVARCHAR (30),
	@ADDRESS_E NVARCHAR (60),
	@USER_E VARCHAR (60),
	@PASS_E NVARCHAR (30),
	@ID INT
AS
BEGIN
INSERT INTO EMPLOYEE VALUES
(
	@NAME_E,
	@EMAIL,
	@ADDRESS_E,
	@USER_E,
	ENCRYPTBYPASSPHRASE('PASSWORD', @PASS_E),
	@ID
)
END
GO

CREATE PROCEDURE REGISTERSITE
	@NAME_S VARCHAR (60),
	@DESCR NVARCHAR (100),
	@PASS_S NVARCHAR (30),
	@ID_EMP INT
AS
BEGIN
INSERT INTO SITEC VALUES
(
	@NAME_S,
	@DESCR,
	ENCRYPTBYPASSPHRASE('PASSWORD',@PASS_S),
	@ID_EMP
)
END
GO

EXEC REGISTERCOMPANY 'ACTIVITION','LOS ANGELES', 'ACTV', '@/*SHEN.ONE-(123)'

EXEC REGISTEREMPLOYEE 'DAN','VIM@GMAIL.COM','MENA 140','DAMIAN','dam.1234',1

EXEC REGISTERSITE 'YOUTUBE','PLATAFORMA DE VIDEOS','CHOLOS',1

SELECT CONVERT(NVARCHAR(MAX), DECRYPTBYPASSPHRASE('PASSWORD', PASS)) FROM COMPANY

SELECT CONVERT(NVARCHAR(MAX), DECRYPTBYPASSPHRASE('PASSWORD', PASS_E)) FROM EMPLOYEE

drop procedure REGISTERCOMPANY

SELECT * FROM COMPANY
SELECT * FROM EMPLOYEE
SELECT * FROM SITEC

drop database EncripPass

select * from COMPANY where USERNAME = 'ACTV' and CONVERT(NVARCHAR(MAX),DECRYPTBYPASSPHRASE('PASSWORD',PASS)) = '@/*SHEN.ONE-(123)'

select * from EMPLOYEE where USER_E = 'DAMIAN' and CONVERT(NVARCHAR(MAX),DECRYPTBYPASSPHRASE('PASSWORD',PASS_E)) = 'dam.1234'